import Foundation

enum AdvancedContent {
    struct ValueCase: Sendable {
        let id: String
        let situation: String
        let base: Int
        let multiplier: Int
        let bid: Int
        let lost: Bool
        let expected: Int
        let reasoning: String

        var question: QuizQuestion {
            let alternatives = lost ? [expected - base * 2, expected + base] : [expected + base, expected - base]
            return AdvancedContent.question(id, situation + " Welcher Listenwert gilt nach internationaler Skatordnung (ohne Turnierbonus)?",
                                            "\(expected)", "\(alternatives[0])", "\(alternatives[1])", reasoning)
        }
    }

    static let valueCases: [ValueCase] = [
        ValueCase(id: "vertieft-wert-01", situation: "Kreuz mit zwei, Skataufnahme, 78 Augen, gereizt 36.", base: 12, multiplier: 3, bid: 36, lost: false, expected: 36, reasoning: "Mit zwei, Spiel drei: 3 × 12 = 36. 78 Augen bringen weder Schneider noch eine Handstufe."),
        ValueCase(id: "vertieft-wert-02", situation: "Pik ohne drei, Skataufnahme, 65 Augen, gereizt 44. Auch im Skat liegt keiner der drei fehlenden höchsten Buben.", base: 11, multiplier: 4, bid: 44, lost: false, expected: 44, reasoning: "Ohne drei, Spiel vier: 4 × 11 = 44. Für die Spitzen zählen Hand und Skat zusammen."),
        ValueCase(id: "vertieft-wert-03", situation: "Herz mit einem, Hand, 74 Augen, gereizt 30. Der Skat ändert die Spitzen nicht.", base: 10, multiplier: 3, bid: 30, lost: false, expected: 30, reasoning: "Mit einem, Spiel zwei, Hand drei: 3 × 10 = 30. Hand ist eine zusätzliche Gewinnstufe."),
        ValueCase(id: "vertieft-wert-04", situation: "Karo ohne zwei, Hand, 82 Augen, gereizt 36. Kein fehlender Spitzentrumpf liegt im Skat.", base: 9, multiplier: 4, bid: 36, lost: false, expected: 36, reasoning: "Ohne zwei, Spiel drei, Hand vier: 4 × 9 = 36. Die Grundwerte der Farben sind verschieden."),
        ValueCase(id: "vertieft-wert-05", situation: "Grand mit zwei, Skataufnahme, 92 Augen, gereizt 72.", base: 24, multiplier: 4, bid: 72, lost: false, expected: 96, reasoning: "Die Gegenpartei hat 28 Augen und ist Schneider. Mit zwei, Spiel drei, Schneider vier: 4 × 24 = 96."),
        ValueCase(id: "vertieft-wert-06", situation: "Kreuz mit einem, Skataufnahme, 90 Augen, gereizt 24.", base: 12, multiplier: 3, bid: 24, lost: false, expected: 36, reasoning: "Bei genau 90 Augen bleiben der Gegenpartei 30, also Schneider. Mit einem, Spiel zwei, Schneider drei: 36."),
        ValueCase(id: "vertieft-wert-07", situation: "Pik mit einem, Skataufnahme, 89 Augen, gereizt 22.", base: 11, multiplier: 2, bid: 22, lost: false, expected: 22, reasoning: "31 Augen der Gegenpartei sind nicht Schneider. Mit einem, Spiel zwei: 22. Die Grenze liegt bei höchstens 30 Augen."),
        ValueCase(id: "vertieft-wert-08", situation: "Herz mit zwei, Hand, Schneider angesagt und mit 93 Augen erreicht, gereizt 50. Die Spitzen sind einschließlich Skat geklärt.", base: 10, multiplier: 6, bid: 50, lost: false, expected: 60, reasoning: "Mit zwei, Spiel drei, Hand vier, Schneider fünf, angesagt sechs: 60. Die Ansage zählt zusätzlich zum erreichten Schneider."),
        ValueCase(id: "vertieft-wert-09", situation: "Karo mit einem, Hand, ohne Ansage alle zehn Stiche gewonnen, gereizt 27.", base: 9, multiplier: 5, bid: 27, lost: false, expected: 45, reasoning: "Mit einem, Spiel zwei, Hand drei, Schneider vier, Schwarz fünf: 45. Schwarz setzt keinen gegnerischen Stich voraus."),
        ValueCase(id: "vertieft-wert-10", situation: "Grand mit vieren, ouvert regelgerecht gewonnen, gereizt 120.", base: 24, multiplier: 11, bid: 120, lost: false, expected: 264, reasoning: "Mit vieren, Spiel fünf, Hand sechs, Schneider sieben, angesagt acht, Schwarz neun, angesagt zehn, ouvert elf: 264. Grand ouvert verlangt alle Stiche."),
        ValueCase(id: "vertieft-wert-11", situation: "Kreuz mit zwei, Skataufnahme, 58 Augen, gereizt 36. Keine Partei ist Schneider.", base: 12, multiplier: 3, bid: 36, lost: true, expected: -72, reasoning: "Das einfache Spiel ist 36 wert. Ein Verlust wird doppelt abgeschrieben: -72, nicht nur -36."),
        ValueCase(id: "vertieft-wert-12", situation: "Pik mit einem, Skataufnahme, 60 Augen, gereizt 22.", base: 11, multiplier: 2, bid: 22, lost: true, expected: -44, reasoning: "60 Augen reichen dem Alleinspieler nicht. Mit einem, Spiel zwei ergibt 22, doppelt verloren also -44."),
        ValueCase(id: "vertieft-wert-13", situation: "Herz ohne zwei, Skataufnahme, nur 29 Augen, gereizt 30. Die Spitzen sind geklärt.", base: 10, multiplier: 4, bid: 30, lost: true, expected: -80, reasoning: "Der Alleinspieler ist selbst Schneider. Ohne zwei, Spiel drei, Schneider vier: 40. Der verlorene Wert wird auf -80 verdoppelt."),
        ValueCase(id: "vertieft-wert-14", situation: "Grand mit einem, Hand, Schneider angesagt, aber nur 89 Augen erreicht, gereizt 72.", base: 24, multiplier: 5, bid: 72, lost: true, expected: -240, reasoning: "Die verpflichtende Schneideransage ist verfehlt. Mit einem, Spiel zwei, Hand drei, Schneider vier, angesagt fünf: 120, doppelt verloren -240."),
        ValueCase(id: "vertieft-wert-15", situation: "Kreuz mit einem, Skataufnahme, 80 Augen, gereizt 30.", base: 12, multiplier: 2, bid: 30, lost: true, expected: -72, reasoning: "Der erreichte Wert 24 deckt 30 nicht. Das kleinste ausreichende Vielfache von 12 ist 36, doppelt abgeschrieben -72. Die Augen heilen das Überreizen nicht."),
        ValueCase(id: "vertieft-wert-16", situation: "Pik mit einem, Skataufnahme, 75 Augen, gereizt 35.", base: 11, multiplier: 2, bid: 35, lost: true, expected: -88, reasoning: "22 ist zu wenig. 33 deckt den Reizwert 35 ebenfalls nicht, also wird 44 angesetzt und doppelt verloren: -88."),
        ValueCase(id: "vertieft-wert-17", situation: "Herz mit einem, Skataufnahme, 70 Augen, gereizt 36.", base: 10, multiplier: 2, bid: 36, lost: true, expected: -80, reasoning: "Das Spiel erreicht nur 20. Das kleinste Herz-Vielfache ab 36 ist 40, deshalb -80."),
        ValueCase(id: "vertieft-wert-18", situation: "Karo mit einem, Skataufnahme, 77 Augen, gereizt 23.", base: 9, multiplier: 2, bid: 23, lost: true, expected: -54, reasoning: "Der einfache Wert ist 18. Das kleinste ausreichende Karo-Vielfache ist 27. Überreizt und doppelt verloren ergibt -54."),
        ValueCase(id: "vertieft-wert-19", situation: "Grand mit einem, Skataufnahme, 81 Augen, gereizt 50.", base: 24, multiplier: 2, bid: 50, lost: true, expected: -144, reasoning: "48 deckt 50 nicht. Das nächste Grand-Vielfache ist 72. Doppelte Abschreibung: -144."),
        ValueCase(id: "vertieft-wert-20", situation: "Karo-Hand: Du hieltest ohne drei und reiztest 36. Im unberührten Skat liegt der Kreuz-Bube, aber nicht der Pik-Bube. Du erreichst 80 Augen.", base: 9, multiplier: 3, bid: 36, lost: true, expected: -72, reasoning: "Der Skat zählt auch beim Handspiel für Spitzen. Nun mit einem, Spiel zwei, Hand drei = 27. 36 wird nicht erreicht, das passende Vielfache 36 wird doppelt abgeschrieben."),
        ValueCase(id: "vertieft-wert-21", situation: "Karo-Hand wie zuvor: Kreuz-Bube im Skat, Pik-Bube fehlt. Gereizt 36, diesmal 92 Augen.", base: 9, multiplier: 4, bid: 36, lost: false, expected: 36, reasoning: "Mit einem, Spiel zwei, Hand drei, tatsächlich Schneider vier: 36. Der erreichte Schneider deckt diesmal den Reizwert."),
        ValueCase(id: "vertieft-wert-22", situation: "Kreuz mit vier Buben und Kreuz-Ass, aber ohne Kreuz-Zehn, Skataufnahme, 76 Augen, gereizt 60.", base: 12, multiplier: 6, bid: 60, lost: false, expected: 72, reasoning: "Die Spitzenfolge endet nicht bei den Buben: Mit fünf, Spiel sechs = 72. Das fehlende Kreuz-Zehn unterbricht die Folge nach dem Ass."),
        ValueCase(id: "vertieft-wert-23", situation: "Herz mit allen vier Buben sowie Herz-Ass und Herz-Zehn, ohne Herz-König, Skataufnahme, 73 Augen, gereizt 60.", base: 10, multiplier: 7, bid: 60, lost: false, expected: 70, reasoning: "Sechs lückenlose Spitzentrümpfe ergeben mit sechs, Spiel sieben: 70. Die Folge endet vor dem fehlenden Herz-König."),
        ValueCase(id: "vertieft-wert-24", situation: "Grand ohne vier Buben in Hand und Skat, Skataufnahme, 67 Augen, gereizt 96.", base: 24, multiplier: 5, bid: 96, lost: false, expected: 120, reasoning: "Im Grand sind nur die Buben Trumpf. Ohne vier, Spiel fünf: 120. Ein Ass verlängert hier keine Spitzenfolge.")
    ]

    static let scoring = valueCases.map(\.question)

    struct PlanningCase: Sendable {
        let id: String
        let trump: Suit?
        let hands: [[PlayingCard]]
        let priorEyes: Int
        let guaranteedEyes: [Int]
        let reasoning: String

        var question: QuizQuestion {
            let game = trump.map { "\($0.displayName)spiel" } ?? "Grand"
            let labels = hands.map { $0.map(\.spokenName).joined(separator: ", ") }
            let prompt = "\(game), noch drei Stiche. Du bist Alleinspieler und spielst aus. \(priorEyes) Augen einschließlich Skat, Reizwert gedeckt. Alle Restkarten sind bekannt:\n\nDu: \(labels[0]).\nLinks: \(labels[1]).\nRechts: \(labels[2]).\n\nWelches Ausspiel erzwingt gegen jede legale Abwehr mindestens 61 Augen?"
            let answerIndex = guaranteedEyes.firstIndex(of: guaranteedEyes.max()!)!
            return QuizQuestion(id: id, prompt: prompt, tiles: hands[0],
                                choices: hands[0].map(\.spokenName), answerIndex: answerIndex,
                                explanation: reasoning)
        }
    }

    static let planningCases: [PlanningCase] = [
        PlanningCase(id: "vertieft-plan-01", trump: .spades,
                     hands: [[.c(10), .s(13), .s(14)], [.s(10), .h(8), .s(9)], [.h(10), .c(14), .d(13)]],
                     priorEyes: 40, guaranteedEyes: [21, 15, 15],
                     reasoning: "Kreuz-Zehn zuerst erzwingt mindestens 21 Restaugen, also 61 insgesamt. Du gibst einen Seitenstich ab, ohne die Trumpfgabel Ass/König früh aufzulösen. Zum Beispiel nimmt der rechte Gegner mit Kreuz-Ass; auf Herz-Zehn stichst du dann mit Pik-Ass. Ein Trumpfausspiel erlaubt den Gegnern dagegen, deine Restbeute auf 15 Augen zu begrenzen."),
        PlanningCase(id: "vertieft-plan-02", trump: .clubs,
                     hands: [[.s(14), .h(12), .s(12)], [.s(13), .s(9), .d(12)], [.s(10), .d(13), .c(14)]],
                     priorEyes: 40, guaranteedEyes: [21, 13, 0],
                     reasoning: "Pik-Ass sofort sichert mindestens 21 Augen: Beide Gegner müssen Pik bedienen. Bei Herz-Dame zuerst kann Kreuz-Ass stechen, danach greift die Gegenpartei deine Pikstruktur an. Du darfst das sichere Ass nicht auf einen späteren Übergang verschieben. Ass-Ausspiel ergibt mindestens 61, die anderen Ausspiele höchstens 53 beziehungsweise 40 gegen beste Abwehr."),
        PlanningCase(id: "vertieft-plan-03", trump: .spades,
                     hands: [[.s(14), .s(8), .d(8)], [.d(10), .h(12), .h(14)], [.s(9), .d(14), .s(7)]],
                     priorEyes: 36, guaranteedEyes: [14, 14, 25],
                     reasoning: "Karo-Acht zuerst gibt das Ausspiel kontrolliert ab. Der rechte Gegner muss Karo-Ass auf Karo-Zehn legen und anschließend in deine Trumpfstruktur oder mit einer abwerfbaren Karo-Karte zurückspielen. So erzwingst du mindestens 25 Augen. Mit einem Trumpf zuerst bleibt dir gegen beste Abwehr nur eine Beute von 14; 36 + 25 gewinnt genau."),
        PlanningCase(id: "vertieft-plan-04", trump: .spades,
                     hands: [[.h(14), .s(9), .c(12)], [.c(7), .d(9), .s(7)], [.d(13), .s(10), .h(13)]],
                     priorEyes: 46, guaranteedEyes: [4, 15, 4],
                     reasoning: "Pik-Neun opfert den Trumpfstich, zieht aber beide fremden Trümpfe. Dadurch wird Herz-Ass gegen Herz-König sicher und liefert mindestens 15 Restaugen. Ein frühes Seitenass kann vom herzfreien linken Gegner gestochen werden. Bei Herz-Ass oder Kreuz-Dame zuerst können die Gegner deine Beute auf vier Augen begrenzen."),
        PlanningCase(id: "vertieft-plan-05", trump: .diamonds,
                     hands: [[.c(11), .h(12), .d(12)], [.d(7), .c(10), .s(11)], [.s(12), .d(8), .c(14)]],
                     priorEyes: 38, guaranteedEyes: [18, 13, 23],
                     reasoning: "Karo-Dame zuerst schafft den nötigen Übergang: Selbst wenn Pik-Bube übernimmt, bleibt Kreuz-Bube für einen späteren Augenstich erhalten. Eine optimale Abwehrlinie ist Pik-Bube, Karo-Acht; dann Kreuz-Zehn, Kreuz-Ass, dein Kreuz-Bube für 23 Augen. Auch andere legale Abwehrlinien lassen mindestens 23 zu. Den höchsten Buben sofort zu ziehen garantiert dagegen nur 18."),
        PlanningCase(id: "vertieft-plan-06", trump: nil,
                     hands: [[.c(10), .h(11), .d(7)], [.d(10), .d(14), .s(11)], [.c(7), .s(12), .d(9)]],
                     priorEyes: 46, guaranteedEyes: [15, 0, 0],
                     reasoning: "Kreuz-Zehn zuerst bietet Augen an, während du Herz-Bube zurückhältst. Übernimmt Pik-Bube, kann die Gegenpartei zwar einen Karostich holen, muss aber später in deinen verbliebenen Buben spielen. Mindestens 15 Augen bleiben sicher. Auf Herz-Bube oder Karo-Sieben zuerst kann die Gegenpartei hingegen sämtliche Restaugen behalten."),
        PlanningCase(id: "vertieft-plan-07", trump: .clubs,
                     hands: [[.h(8), .c(13), .h(13)], [.c(11), .h(12), .d(7)], [.d(14), .d(12), .s(10)]],
                     priorEyes: 41, guaranteedEyes: [0, 0, 20],
                     reasoning: "Herz-König zuerst hält das Ausspiel: Der linke Gegner muss Herz-Dame bedienen, der rechte ist trumpffrei. Danach gewinnst du mit Herz-Acht einen weiteren Seitenstich. Beide zusammen bringen gegen jede Abwehr mindestens 20 Augen. Herz-Acht zuerst gibt der Dame das Ausspiel, Kreuz-König läuft in Kreuz-Bube. Beide falschen Eröffnungen erlauben null eigene Restaugen."),
        PlanningCase(id: "vertieft-plan-08", trump: .diamonds,
                     hands: [[.s(8), .s(14), .d(12)], [.s(12), .c(8), .c(11)], [.d(11), .h(12), .h(14)]],
                     priorEyes: 44, guaranteedEyes: [0, 0, 17],
                     reasoning: "Karo-Dame zwingt beide gegnerischen Buben in einen Stich und macht später Pik-Ass nutzbar. Eine optimale Abwehrlinie ist Kreuz-Bube, Karo-Bube; danach Kreuz-Acht, Herz-Ass, Pik-Acht; zuletzt Pik-Dame, Herz-Dame, Pik-Ass für 17 Augen. Über alle legalen Abwehrlinien bleiben mindestens diese 17 sicher. Ein Pik-Ausspiel zuerst lässt die Gegenpartei alle Restaugen gewinnen.")
    ]

    static let planning = planningCases.map(\.question)

    static let defense: [QuizQuestion] = [
        question("vertieft-abwehr-01", "Grand, letzter Stich. Dein Partner spielt Karo-Ass, der Alleinspieler legt Karo-König. Du hast nur Karo-Zehn. Eure Partei hatte 35 Augen. Wie endet das Spiel?", "Gegenpartei gewinnt mit 60", "Alleinspieler gewinnt mit 61", "Gegenpartei bleibt bei 49", "11 + 4 + 10 = 25 Augen im Stich. 35 + 25 = 60 genügt der Gegenpartei. Der Alleinspieler bleibt bei 60.", [.d(14), .d(13), .d(10)]),
        question("vertieft-abwehr-02", "Herzspiel. Du bist Hinterhand, Partner hat Kreuz-Ass gespielt, Alleinspieler Kreuz-König. Deine vollständige Resthand: Kreuz-Zehn, Kreuz-Sieben, Karo-Ass. Keine Karte folgt nach dir. Welche Zugabe bringt eurer Partei hier die meisten Augen?", "Kreuz-Zehn", "Karo-Ass", "Kreuz-Sieben", "Kreuz muss bedient werden. Das Ass des Partners steht fest; die Zehn sichert zehn zusätzliche Augen. Das Karo-Ass wäre ein Bedienfehler.", [.c(10), .c(7), .d(14)]),
        question("vertieft-abwehr-03", "Grand. Partner spielt Herz-Ass, Alleinspieler sticht mit Karo-Bube. Du bist Hinterhand, herzfrei, mit Pik-Bube und Karo-Zehn. Welche Karte sichert diesen Augenstich für euch?", "Pik-Bube", "Karo-Zehn", "Beide Karten gewinnen", "Pik-Bube steht über Karo-Bube. Die Zehn ist nur eine Seitenkarte und würde dem Alleinspieler zehn Augen schenken.", [.s(11), .d(10)]),
        question("vertieft-abwehr-04", "Pikspiel. Partner spielt Kreuz-Ass, Alleinspieler Kreuz-Acht. Du bist Hinterhand und kreuzfrei. Resthand: Karo-Zehn, Pik-Sieben. Welche Karte bringt in diesem bereits sicheren Partnerstich mehr Augen?", "Karo-Zehn schmieren", "Pik-Sieben stechen", "Beide bringen zehn Augen", "Der Alleinspieler hat bedient und kann nicht mehr stechen. Die Zehn bringt zehn Augen in den Partnerstich, ohne deinen Trumpf zu verbrauchen.", [.d(10), .s(7)]),
        question("vertieft-abwehr-05", "Herzspiel. Partner spielt Karo-Ass, Alleinspieler Karo-Neun. Du hältst in Hinterhand Karo-Sieben und Kreuz-Zehn. Darfst du die Zehn schmieren?", "Nein, Karo-Sieben ist Pflicht", "Ja, weil der Partner gewinnt", "Ja, weil die Zehn Augen zählt", "Ein sicherer Partnerstich hebt die Bedienpflicht nicht auf. Mit Karo auf der Hand musst du Karo zugeben.", [.d(7), .c(10)]),
        question("vertieft-abwehr-06", "Grand. Im bisherigen Spiel sind Kreuz-, Pik- und Herz-Bube gefallen. Du hältst Karo-Bube. Wie viele fremde Trümpfe sind noch möglich?", "Keine", "Einer", "Drei", "Es gibt genau vier Grandtrümpfe. Drei sind gefallen, den vierten hältst du selbst. Karo-Bube ist nun der höchste verbleibende Trumpf.", [.d(11)]),
        question("vertieft-abwehr-07", "Kreuzspiel. Alle vier Buben sowie Kreuz-Ass und Kreuz-Zehn sind gefallen. Du hältst Kreuz-Dame und Kreuz-Neun. Welche höhere Trumpfkarte kann noch ausstehen?", "Nur Kreuz-König", "Kreuz-Bube und Kreuz-König", "Keine", "Nach den Buben gilt Ass, Zehn, König, Dame, Neun, Acht, Sieben. Über deiner Dame bleibt aus der genannten Liste nur der König."),
        question("vertieft-abwehr-08", "Pikspiel. Du warst mit fünf Trümpfen gestartet. Nach zwei vollen Trumpfstichen mit jeweils drei Trümpfen hast du noch drei. Wie viele Trümpfe sind insgesamt außerhalb deiner Hand noch nicht gefallen?", "Zwei", "Drei", "Fünf", "Ein Farbspiel hat elf Trümpfe. Sechs sind gefallen, drei hältst du: 11 - 6 - 3 = 2. Diese zwei können beim Alleinspieler, Partner oder im Skat liegen."),
        question("vertieft-abwehr-09", "Grand. Alleinspieler spielt Kreuz-Ass. Dein Partner ist kreuzfrei und legt Herz-Sieben ab. Was ist allein daraus sicher ableitbar?", "Er hat keine Kreuz-Seitenkarte", "Er hat keinen Buben", "Er hält Herz-Ass", "Kreuz-Bube ist im Grand Trumpf, keine Kreuz-Seitenkarte. Der Abwurf beweist Kreuzfreiheit, nicht Trumpffreiheit oder einen bestimmten Herzbestand."),
        question("vertieft-abwehr-10", "Herzspiel. Alleinspieler spielt Herz-Sieben. Dein Partner legt Karo-Acht ab. Welche sichere Folgerung gilt bei regelgerechtem Spiel?", "Partner hat weder Buben noch Herz", "Partner hat nur keinen Herz-Buben", "Partner hat keine Karo-Karte", "Herz-Sieben fordert Trumpf. Alle Buben gehören zur Trumpffarbe; wer abwirft, hält keinen einzigen Trumpf mehr."),
        question("vertieft-abwehr-11", "Grand. Alleinspieler spielt Kreuz-Sieben. Dein Partner legt Kreuz-Bube. Er hat laut offener Resthand auch Kreuz-König. Ist das legal?", "Nein, Kreuz-König muss folgen", "Ja, beide Karten zeigen Kreuz", "Ja, Buben dürfen immer gespielt werden", "Der Bube ist Trumpf. Eine Kreuz-Seitenkarte ist vorhanden, also muss sie bedient werden. Das aufgedruckte Symbol genügt nicht."),
        question("vertieft-abwehr-12", "Grand. Partner spielt Kreuz-Bube, Alleinspieler Herz-Bube. Du hältst Karo-Bube und Karo-Ass. Welche Karte musst du in Hinterhand zugeben?", "Karo-Bube", "Karo-Ass", "Du darfst wählen", "Ein Bube fordert Trumpf. Dein Karo-Bube muss folgen, obwohl er den Partner nicht überholt. Das Ass ist kein Trumpf.", [.d(11), .d(14)]),
        question("vertieft-abwehr-13", "Grand, Hinterhand. Alleinspieler spielt Herz-Ass, Partner legt Herz-Zehn. Du bist herzfrei und hast nur Karo-Bube oder Kreuz-Sieben zur Wahl. Welche Karte verhindert, dass 21 Augen an den Alleinspieler gehen?", "Karo-Bube", "Kreuz-Sieben", "Keine, das Ass ist unschlagbar", "Der Bube sticht das Ass und sichert 23 Augen für eure Partei. Kreuz-Sieben ist ein Abwurf, kein Stichgewinn.", [.d(11), .c(7)]),
        question("vertieft-abwehr-14", "Karo, Hinterhand. Alleinspieler spielt Pik-Ass, Partner sticht mit Herz-Bube. Du bist pikfrei; Resthand Kreuz-Bube und Herz-Zehn. Was sichert mehr Augen, ohne einen hohen Trumpf zu verbrauchen?", "Herz-Zehn abwerfen", "Kreuz-Bube überstechen", "Beides bringt gleich viele Augen", "Der Partner hat den Stich bereits gewonnen. Die Herz-Zehn schmiert zehn Augen. Überstechen wäre legal, kostet aber den höchsten Trumpf und bringt nur zwei.", [.c(11), .h(10)]),
        question("vertieft-abwehr-15", "Grand. Eure Partei hat 48 Augen. Partner spielt Pik-Ass, Alleinspieler Pik-Sieben. Du bist Hinterhand mit Pik-Dame und Pik-Acht. Welche Zugabe erreicht sofort die Gewinnschwelle?", "Pik-Dame", "Pik-Acht", "Keine der beiden", "Mit der Dame: 48 + 11 + 3 = 62. Mit der Acht: nur 59. Beide bedienen, aber nur die Dame entscheidet sofort.", [.s(12), .s(8)]),
        question("vertieft-abwehr-16", "Grand. Eure Partei hat 40 Augen. Partner spielt Karo-Ass, Alleinspieler Karo-König. Du hältst in Hinterhand Karo-Zehn und Karo-Neun. Welche Zugabe gewinnt sofort das Spiel?", "Karo-Zehn", "Karo-Neun", "Beide", "40 + 11 + 4 + 10 = 65. Mit der Neun wären es 55. Die Zehn darf unter das höhere Ass geschmiert werden.", [.d(10), .d(9)]),
        question("vertieft-abwehr-17", "Pikspiel. Du hast Kreuz-Bube und Pik-Ass. Alleinspieler hat Pik-Zehn ausgespielt. Du bist Mittelhand. Welche deiner Karten muss nach internationaler Bedienregel gespielt werden?", "Eine der beiden, du darfst wählen", "Immer Kreuz-Bube", "Immer Pik-Ass", "Beide sind Pik-Trümpfe und bedienen. Es gibt keine allgemeine Pflicht zu stechen oder den höchsten Trumpf zu wählen. Eine taktische Bewertung bräuchte den dritten Spieler.", [.c(11), .s(14)]),
        question("vertieft-abwehr-18", "Grand. Alleinspieler spielt Karo-Ass, Partner Karo-Zehn. Du bist Hinterhand mit Karo-Dame und Kreuz-Bube. Warum darfst du nicht mit dem Buben die 21 Augen retten?", "Du musst die Karo-Dame bedienen", "Kreuz-Bube ist zu niedrig", "Im Grand darf man nicht stechen", "Eine vorhandene Seitenfarbe muss bedient werden. Der Bube könnte den Stich schlagen, ist aber in dieser Lage keine legale Zugabe.", [.d(12), .c(11)]),
        question("vertieft-abwehr-19", "Herzspiel. Partner spielt Pik-Ass, Alleinspieler Pik-Zehn. Du hast als Hinterhand nur Kreuz-Zehn und Karo-Zehn. Was lässt sich über die bessere Zugabe allein hier sagen?", "Für diesen Stich sind beide gleichwertig", "Kreuz-Zehn ist immer besser", "Karo-Zehn ist immer besser", "Beide Abwürfe sind legal und bringen zehn Augen. Welche Farbe später wertvoller ist, ist ohne Restkarten nicht bestimmbar. Genau dieser Kontext fehlt bei pauschalen Drück- oder Abwurfregeln.", [.c(10), .d(10)]),
        question("vertieft-abwehr-20", "Grand, letzter Stich. Partner spielt Kreuz-Ass, Alleinspieler Kreuz-Zehn, du Kreuz-König. Eure Partei hatte 34 Augen. Gewinnt die Gegenpartei?", "Nein, sie endet bei 59", "Ja, sie endet bei 60", "Ja, sie endet bei 61", "Der Stich zählt 25, also insgesamt 59. Der Alleinspieler hat die übrigen 61 Augen einschließlich Skat und gewinnt bei gedecktem Reizwert.", [.c(14), .c(10), .c(13)])
    ]

    static let nullPlay: [QuizQuestion] = [
        question("vertieft-null-01", "Null ouvert, nur noch ein Stich. Alleinspieler spielt Kreuz-Neun, du bist Mittelhand mit Kreuz-Acht, Partner hat nur Kreuz-Sieben. Wer gewinnt den Stich?", "Alleinspieler, Null verloren", "Du mit Kreuz-Acht", "Partner mit Kreuz-Sieben", "Alle bedienen Kreuz. Neun ist höher als Acht und Sieben. Der Alleinspieler erhält einen Stich und verliert unabhängig von Augen.", [.c(9), .c(8), .c(7)]),
        question("vertieft-null-02", "Null ouvert. Du spielst Kreuz-Acht, der Alleinspieler in Mittelhand hat als einzige Kreuzkarte Kreuz-Neun. Partner ist kreuzfrei und hat Pik-Ass. Was passiert in diesem Stich?", "Kreuz-Neun gewinnt, Null verloren", "Pik-Ass gewinnt", "Kreuz-Acht gewinnt", "Die Neun muss bedienen und schlägt die Acht. Ein fremdes Ass ist im Null kein Trumpf und kann den Kreuzstich nicht übernehmen."),
        question("vertieft-null-03", "Null ouvert, letzter Stich. Partner spielt Herz-Zehn, Alleinspieler Herz-Bube, du Herz-Dame. Bleibt Null in diesem Stich erhalten?", "Ja, Herz-Dame gewinnt", "Nein, Herz-Bube ist Trumpf", "Nein, Herz-Zehn ist höher als Dame", "Im Null lautet die Folge Zehn, Bube, Dame, König, Ass aufsteigend. Die Dame übernimmt den Buben. Der Alleinspieler bleibt stichlos.", [.h(10), .h(11), .h(12)]),
        question("vertieft-null-04", "Null ouvert. Partner spielt Pik-Sieben, Alleinspieler Pik-Zehn. Du hast Pik-Neun und Pik-Bube. Welche Zugabe zwingt den Alleinspieler in diesen Stich?", "Pik-Neun", "Pik-Bube", "Beide", "Die Neun bleibt unter der Zehn, sodass der Alleinspieler gewinnt. Der Bube würde im Null über der Zehn stehen und ihn retten.", [.s(9), .s(11)]),
        question("vertieft-null-05", "Null ouvert, Hinterhand. Partner spielt Karo-Acht, Alleinspieler Karo-Dame. Deine Resthand: Karo-Bube und Karo-König. Welche Karte lässt den Alleinspieler gewinnen?", "Karo-Bube", "Karo-König", "Keine", "Bube liegt unter Dame; König liegt darüber. Den König zugeben würde den Alleinspieler retten, der Bube lässt die Dame den Stich erhalten.", [.d(11), .d(13)]),
        question("vertieft-null-06", "Null ouvert. Alleinspieler ist kreuzfrei und wirft Herz-Ass auf Kreuz-Sieben und Kreuz-Acht ab. Verliert er allein wegen des Asses?", "Nein, die Kreuz-Acht gewinnt", "Ja, jedes Ass verliert Null", "Ja, Herz-Ass ist Trumpf", "Eine fremde Farbe kann im Null nicht stechen. Hohe Karten sind beim legalen Abwurf ungefährlich. Entscheidend ist, wer den Stich gewinnt."),
        question("vertieft-null-07", "Null ouvert, letzter Stich. Du spielst Karo-Sieben, Alleinspieler hat Karo-Acht, Partner Karo-Ass. Könnt ihr den Alleinspieler zwingen?", "Nein, Partner muss mit Ass übernehmen", "Ja, Partner darf passen", "Ja, Partner darf das Ass verstecken", "Der Partner hat nur das Ass und muss es spielen. Es übernimmt die Acht. Im vollständigen letzten Stich ist der Angriff damit widerlegt.", [.d(7), .d(8), .d(14)]),
        question("vertieft-null-08", "Null ouvert. Du bist Alleinspieler in Hinterhand. Vor dir liegen Kreuz-Neun und Kreuz-Bube. Du hast Kreuz-Zehn und Kreuz-Dame. Welche Zugabe vermeidet einen eigenen Stich?", "Kreuz-Zehn", "Kreuz-Dame", "Beide", "Im Null liegt die Zehn unter dem Buben, die Dame darüber. Mit der Zehn bleibt der Bube beim Gegner; mit der Dame würdest du gewinnen.", [.c(10), .c(12)]),
        question("vertieft-null-09", "Null ouvert. Du bist Alleinspieler in Hinterhand. Karo-Zehn und Karo-Dame liegen im Stich. Du hältst Karo-Bube und Karo-König. Was hält dich stichlos?", "Karo-Bube", "Karo-König", "Keine Karte", "Die Dame ist höher als dein Bube, aber niedriger als dein König. Du musst Karo bedienen und wählst den Buben.", [.d(11), .d(13)]),
        question("vertieft-null-10", "Null ouvert. Du bist Alleinspieler in Hinterhand. Herz-Ass und Herz-Sieben liegen im Stich. Du hast Herz-König und Herz-Acht. Welche legalen Karten vermeiden den eigenen Stich?", "Beide", "Nur Herz-Acht", "Nur Herz-König", "Das Ass steht im Null über beiden. Beide bedienen und bleiben unter dem Ass. Die kleinste Karte ist nicht automatisch die einzige sichere Zugabe.", [.h(13), .h(8)]),
        question("vertieft-null-11", "Null ouvert. Du spielst Kreuz-Sieben an. Alleinspieler in Mittelhand hält Kreuz-Acht und Kreuz-Dame. Partner hat ausschließlich Kreuz-Neun in dieser Farbe. Ist ein eigener Stich des Alleinspielers sofort erzwungen?", "Nein, er kann Kreuz-Acht legen", "Ja, jede Kreuzkarte gewinnt", "Ja, weil die Dame sichtbar ist", "Mit der Acht übernimmt später die Neun des Partners. Die offene Dame allein garantiert keinen sofortigen Zwang; die niedrige Deckkarte schützt diesen Stich."),
        question("vertieft-null-12", "Null ouvert. Du spielst Kreuz-Neun. Alleinspieler in Mittelhand hat nur Kreuz-Zehn. Partner kann Kreuz-Acht oder Kreuz-Dame bedienen. Was muss Partner legen, um Null zu schlagen?", "Kreuz-Acht", "Kreuz-Dame", "Beide gewinnen für euch", "Die Acht bleibt unter der erzwungenen Zehn des Alleinspielers. Die Dame würde den Stich selbst übernehmen und Null retten.", [.c(8), .c(12)]),
        question("vertieft-null-13", "Du hast 24 gehalten, den Skat aufgenommen und willst einfaches Null ansagen. Warum kann stichloses Spielen diesen Plan nicht retten?", "Der feste Nullwert 23 deckt 24 nicht", "Null verlangt mindestens 61 Augen", "Jeder Bube im Skat verliert Null", "Die Nullansage ist durch 24 nicht mehr gedeckt. Nach ISkO 3.6.2 wird ein nicht mehr durchführbares Null als verlorenes Farb- oder Grandspiel unter Berücksichtigung von Reizhöhe und Spitzen gewertet, nicht pauschal als -46."),
        question("vertieft-null-14", "Null-Hand, gereizt 35. Der Alleinspieler bleibt stichlos. Welcher Listenwert gilt?", "+35", "+46", "+23", "Null-Hand hat den festen Wert 35. Keine Spitzen- oder Schneiderstufe wird addiert. Der Reizwert ist genau gedeckt."),
        question("vertieft-null-15", "Null ouvert mit Skataufnahme, gereizt 46. Der Alleinspieler erhält einen Stich mit null Augen. Welcher Listenwert gilt?", "-92", "0", "-46", "Jeder eigene Stich verliert Null, auch drei kleine Karten ohne Augen. Der feste Wert 46 wird doppelt abgeschrieben."),
        question("vertieft-null-16", "Null ouvert Hand, gereizt 59. Der Alleinspieler bleibt stichlos. Welche Wertung gilt?", "+59", "+118", "+69", "Null ouvert Hand zählt fest 59. Das offene Handspiel bekommt keine zusätzlichen Spitzen oder Augenstufen."),
        question("vertieft-null-17", "Du hast 36 gehalten, den Skat nicht angesehen und planst Null-Hand. Welche Nullvariante kann diesen Reizwert noch decken, wenn du weiterhin nicht aufnehmen willst?", "Null ouvert Hand für 59", "Einfaches Null-Hand für 35", "Einfaches Null für 23", "36 liegt über 35. Null ouvert Hand hat fest 59, setzt aber offene Karten voraus. Die Wertdeckung allein beweist noch nicht, dass dein Blatt diese offene Variante gewinnt."),
        question("vertieft-null-18", "Du hast 48 gehalten und den Skat aufgenommen. Deckt irgendeine zulässige Nullvariante diesen Reizwert noch?", "Nein, nach Aufnahme maximal 46", "Ja, Null ouvert Hand zählt 59", "Ja, Null ouvert zählt 48", "Nach Skataufnahme sind Handspiele unzulässig. Null ouvert zählt 46 und reicht nicht. Es bleibt die Prüfung eines ausreichend wertvollen Farb- oder Grandspiels, keine nachträgliche Handansage."),
        question("vertieft-null-19", "Null ouvert. Du hältst nur Kreuz-Bube und Herz-Acht. Herz-Sieben ist angespielt. Welche Karte ist legal?", "Nur Herz-Acht", "Nur Kreuz-Bube", "Beide", "Im Null ist der Bube eine Kreuzkarte, kein Trumpf. Mit Herz auf der Hand musst du Herz bedienen. Die niedrige Acht ist hier dennoch höher als die angespielte Sieben.", [.c(11), .h(8)]),
        question("vertieft-null-20", "Null ouvert. Du spielst Pik-Sieben, Alleinspieler legt Pik-Neun. Partner hält Pik-Acht und Pik-Zehn. Welche Karte beendet Null zu euren Gunsten?", "Pik-Acht", "Pik-Zehn", "Beide", "Die Acht lässt die Neun beim Alleinspieler. Die Zehn würde den Stich übernehmen. Auch eine augenlose Neun kann den entscheidenden Nullverlust verursachen.", [.s(8), .s(10)])
    ]

    static let endgames: [QuizQuestion] = [
        question("vertieft-ende-01", "Grand, letzter Stich. Du bist Alleinspieler mit 50 Augen einschließlich Skat. Du spielst Herz-Ass, Gegner geben Herz-Sieben und Herz-Acht. Reicht das bei gedecktem Reizwert?", "Ja, genau 61", "Nein, nur 60", "Nein, das Ass zählt zehn", "Das Ass bringt elf, die kleinen Karten null. 50 + 11 = 61 gewinnt. Der Skat wurde schon mitgezählt und darf nicht noch einmal addiert werden.", [.h(14), .h(7), .h(8)]),
        question("vertieft-ende-02", "Grand, letzter Stich. Du hast 49 Augen einschließlich Skat und gewinnst Karo-Ass, Karo-Sieben, Karo-Acht. Was ist das Ergebnis?", "Verloren mit 60 Augen", "Gewonnen mit 61 Augen", "Unentschieden", "49 + 11 = 60 reicht dem Alleinspieler nicht. Die Gegenpartei hat die anderen 60 und gewinnt.", [.d(14), .d(7), .d(8)]),
        question("vertieft-ende-03", "Pikspiel, letzter Stich. Du hast 45 Augen einschließlich Skat. Du spielst Kreuz-Ass, Gegner geben Kreuz-Zehn und Pik-Sieben. Wer gewinnt?", "Gegenpartei, Pik-Sieben sticht", "Du, Kreuz-Ass ist am höchsten", "Du, weil 66 Augen reichen", "Pik ist Trumpf. Die kleine Pik-Sieben schlägt beide Kreuzkarten und nimmt 21 Augen mit. Deine 45 bleiben unverändert.", [.c(14), .c(10), .s(7)]),
        question("vertieft-ende-04", "Grand, letzter Stich. Du hast 44 Augen einschließlich Skat. Herz-Ass, Herz-Zehn und dein Karo-Bube liegen in dieser Reihenfolge. Wie viele Augen hast du danach?", "67", "65", "46", "Karo-Bube ist Trumpf und gewinnt 11 + 10 + 2 = 23 Augen. 44 + 23 = 67. Ein höherer Bube kann im bereits vollständigen Stich nicht mehr auftauchen.", [.h(14), .h(10), .d(11)]),
        question("vertieft-ende-05", "Grand, letzter Stich. Du bist Alleinspieler und spielst Herz-Zehn. Gegner legen Herz-König und Herz-Dame. Du hattest 44 Augen inklusive Skat. Wie endet es bei gedecktem Reizwert?", "Gewonnen mit 61", "Verloren mit 58", "Gewonnen mit 65", "Die Zehn steht im Grand über König und Dame. Der Stich bringt 10 + 4 + 3 = 17 Augen, also 61. Nicht mit der Null-Reihenfolge verwechseln.", [.h(10), .h(13), .h(12)]),
        question("vertieft-ende-06", "Herzspiel. Vor dem letzten Stich hast du 58 Stichaugen, noch ohne den verdeckten Skat. Du verlierst den letzten Stich. Im Skat liegen Kreuz-Dame und Karo-Sieben. Ist die Augenbedingung erfüllt?", "Ja, 61 einschließlich Skat", "Nein, 58", "Nein, der Skat zählt nur bei Hand", "Die gedrückte Dame zählt drei, die Sieben null. 58 + 3 = 61. Der Skat gehört bei Farbe und Grand zu den Augen des Alleinspielers."),
        question("vertieft-ende-07", "Grand-Hand. Du hast 56 Stichaugen und verlierst den letzten Stich. Im bis dahin unbekannten Skat liegen Herz-König und Karo-Sieben. Reicht das?", "Nein, insgesamt 60", "Ja, Hand gewinnt mit 60", "Ja, insgesamt 61", "Auch bei Hand zählen die Skataugen. 56 + 4 = 60 reicht trotzdem nicht. Hand erhöht den Spielwert, nicht die Gewinnschwelle."),
        question("vertieft-ende-08", "Kreuzspiel, letzte zwei Stiche, vollständige Restkarten. Du hast Kreuz-Bube und Karo-Ass. Linker Gegner Kreuz-Sieben und Herz-Zehn, rechter Kreuz-Acht und Pik-König. Du spielst aus. Welches Ausspiel sichert beide Stiche?", "Kreuz-Bube", "Karo-Ass", "Keines", "Der Bube zieht beide letzten gegnerischen Trümpfe. Danach läuft Karo-Ass gegen die fremden Seitenkarten. Mit Karo-Ass zuerst könnten die karofreien Gegner stattdessen stechen.", [.c(11), .d(14)]),
        question("vertieft-ende-09", "Grand, letzte zwei Stiche, vollständige Restkarten. Du hast Kreuz-Bube und Herz-Ass. Linker Gegner Pik-Bube und Pik-Zehn, rechter Herz-Bube und Karo-König. Du spielst aus. Was sichert alle Restaugen?", "Kreuz-Bube zuerst", "Herz-Ass zuerst", "Beides sicher", "Trumpf ausspielen zwingt beide gegnerischen Buben in einen Stich. Danach ist Herz-Ass sicher. Auf Herz-Ass können die herzfreien Gegner stattdessen ihre Buben einsetzen.", [.c(11), .h(14)]),
        question("vertieft-ende-10", "Herzspiel, letzte zwei Stiche. Du hast Herz-Ass und Karo-Ass. Linker Gegner Herz-Zehn und Pik-König, rechter Herz-König und Kreuz-Zehn. Du spielst aus. Welche Reihenfolge sichert beide Stiche?", "Herz-Ass, dann Karo-Ass", "Karo-Ass, dann Herz-Ass", "Keine Reihenfolge", "Herz-Ass zieht die zwei fremden Resttrümpfe. Erst danach ist dein Seitenass sicher. Beim ersten Karo-Ausspiel könnten die karofreien Gegner stechen.", [.h(14), .d(14)]),
        question("vertieft-ende-11", "Grand, letzte zwei Stiche. Du hast Pik-Bube und Karo-Ass. Linker Gegner Kreuz-Bube und Karo-Sieben, rechter Karo-Zehn und Karo-König. Du spielst aus. Kannst du gegen beste Abwehr beide Stiche erzwingen?", "Nein, Kreuz-Bube verhindert das", "Ja, Pik-Bube zieht alles", "Ja, Karo-Ass zieht den Buben", "Der höhere Kreuz-Bube bleibt ein sicherer gegnerischer Trumpf. Ein Seitenass kann gestochen werden, dein Pik-Bube wird überstochen. Beide Reststiche sind nicht erzwingbar.", [.s(11), .d(14)]),
        question("vertieft-ende-12", "Grand, letzter Stich. Du spielst Pik-Bube, linker Gegner Kreuz-Bube, rechter Karo-Ass. Wer bekommt die 15 Augen?", "Linker Gegner", "Du", "Rechter Gegner", "Zwei Buben zählen je zwei, das Ass elf. Kreuz-Bube schlägt Pik-Bube; die Gegenpartei bekommt den vollständigen Stich.", [.s(11), .c(11), .d(14)]),
        question("vertieft-ende-13", "Kreuzspiel, letzter Stich. Kreuz-Ass, Kreuz-Zehn und Herz-Bube liegen in dieser Reihenfolge. Warum gewinnt der Herz-Bube?", "Jeder Bube steht über Farbtrümpfen", "Herz ist stärker als Kreuz", "Er zählt die meisten Augen", "Die Buben bilden die höchste Trumpfgruppe. Das Ass und die Zehn sind ebenfalls Trumpf, stehen aber unter jedem Buben. Der Stich enthält 23 Augen.", [.c(14), .c(10), .h(11)]),
        question("vertieft-ende-14", "Grand, letzte zwei Stiche. Du hast Kreuz-Ass und Kreuz-Zehn. Linker Gegner Kreuz-König und Kreuz-Dame, rechter Kreuz-Neun und Kreuz-Acht. Keine Buben mehr im Spiel. Du spielst aus. Wie viele Augen sind dir sicher?", "28", "21", "18", "Alle müssen beide Male Kreuz bedienen. Ass und Zehn gewinnen beide Stiche: 11 + 10 + 4 + 3 = 28. Die kleinen Karten bringen null.", [.c(14), .c(10)]),
        question("vertieft-ende-15", "Grand, letzte zwei Stiche. Du hast Herz-Zehn und Herz-König. Linker Gegner Herz-Ass und Herz-Sieben, rechter Herz-Dame und Herz-Acht. Keine Buben mehr. Du spielst aus. Können beide Reststiche dir gehören?", "Nein, Herz-Ass muss einen gewinnen", "Ja, Zehn steht über Ass", "Ja, König zieht das Ass unter", "Das Ass ist die höchste Seitenkarte. Da alle nur Herz halten, bleibt ein gegnerischer Assstich unvermeidbar. Zehn steht über König, nicht über Ass.", [.h(10), .h(13)]),
        question("vertieft-ende-16", "Pikspiel, letzte zwei Stiche. Du hältst Kreuz-Bube und Pik-Ass. Linker Gegner Pik-Zehn und Pik-König, rechter Pik-Dame und Pik-Neun. Du spielst aus. Können Gegner noch einen Stich gewinnen?", "Nein, beide eigenen Trümpfe stehen", "Ja, Pik-Zehn schlägt Pik-Ass", "Ja, Pik-Dame schlägt Kreuz-Bube", "Beide deiner Karten sind höher als jede gegnerische Restkarte. In zwei reinen Trumpfstichen gewinnst du unabhängig von deren Zugaben.", [.c(11), .s(14)]),
        question("vertieft-ende-17", "Herz-Hand, Schneider angesagt. Nach allen Stichen und Skat hast du 89 Augen. Der Reizwert wäre schon ohne Schneider gedeckt. Gewonnen?", "Nein, Ansage verfehlt", "Ja, mehr als 60", "Ja, Hand genügt", "Eine angekündigte Gewinnstufe ist verpflichtend. 31 gegnerische Augen verfehlen Schneider. Ein niedriger Reizwert rettet die verfehlte Ansage nicht."),
        question("vertieft-ende-18", "Grand, Skataufnahme. Du erreichst 120 Augen, die Gegner haben aber einen Stich aus drei kleinen Karten gemacht. Welche zusätzliche Gewinnstufe ist erreicht?", "Schneider, nicht Schwarz", "Schwarz", "Keine", "Schwarz verlangt, dass die Gegenpartei keinen einzigen Stich bekommt. Ein Nullaugenstich verhindert Schwarz, selbst bei 120 Augen des Alleinspielers."),
        question("vertieft-ende-19", "Karo, Skataufnahme. Du hast 61 Augen einschließlich Skat erreicht, aber der Spielwert ist 18 und du hast 20 gehalten. Gewonnen?", "Nein, überreizt", "Ja, 61 Augen genügen immer", "Unentschieden", "Augenbedingung und Reizdeckung müssen beide erfüllt sein. 18 deckt 20 nicht. Für die Abschreibung gilt mindestens 27 als passendes Karo-Vielfaches, doppelt also -54."),
        question("vertieft-ende-20", "Grand, letzte zwei Stiche, du bist Alleinspieler in Hinterhand. Linker Gegner spielt Herz-Ass, rechter Herz-Zehn. Deine Resthand Kreuz-Bube und Karo-Sieben, du bist herzfrei. Du hattest 40 Augen inklusive Skat. Welche Zugabe sichert den Sieg sofort?", "Kreuz-Bube", "Karo-Sieben", "Keine", "Der Bube sticht 23 Augen: 40 + 23 = 63. Ein Abwurf lässt die 21 Augen bei der Gegenpartei. Du brauchst keine Vermutung über den letzten Stich.", [.c(11), .d(7)])
    ]

    static let discards: [DiscardScenario] = [
        DiscardScenario(id: "vertieft-druecken-01", situation: "Grand, Vorhand, gereizt 48. Lehrziel: Alle vier Buben und beide Asse behalten, dabei möglichst viele Augen drücken. Welches Paar erfüllt genau dieses Ziel?", deal: [.c(11), .s(11), .h(11), .d(11), .c(14), .s(14), .h(10), .d(10), .c(13), .s(13), .h(7), .d(8)], recommendedDiscard: [.h(10), .d(10)], reasoning: "Die beiden Zehnen sichern 20 Augen im Skat. Unter der ausdrücklichen Vorgabe, Buben und Asse zu behalten, ist kein höheres Paar möglich. Kleine Karten drücken würde hier null Augen sichern.", tip: "Das ist eine Optimierungsaufgabe mit Vorgabe, keine Behauptung, dass Zehnen in jedem Grand gedrückt gehören."),
        DiscardScenario(id: "vertieft-druecken-02", situation: "Herz, Mittelhand, gereizt 40. Lehrziel: Alle sieben Trümpfe behalten und nach dem Drücken kreuzfrei sein. Wähle das einzige passende Paar.", deal: [.c(11), .s(11), .h(11), .d(11), .h(14), .h(10), .h(7), .c(10), .c(13), .s(14), .d(14), .d(7)], recommendedDiscard: [.c(10), .c(13)], reasoning: "Kreuz-Zehn und Kreuz-König sind die einzigen Kreuz-Seitenkarten. Beide zu drücken schafft Kreuzfreiheit und sichert 14 Augen. Kreuz-Bube bleibt als Herztrumpf erhalten.", tip: "Farbfreisein bezieht sich auf Seitenkarten. Ein Kreuz-Bube macht dich im Herzspiel nicht kreuzpflichtig."),
        DiscardScenario(id: "vertieft-druecken-03", situation: "Null mit Skataufnahme, Hinterhand, gereizt 23. Lehrziel: Beide Asse entfernen, die niedrigen Folgen bleiben zusammen. Wähle das Paar.", deal: [.c(7), .c(8), .c(9), .c(10), .s(7), .s(8), .s(9), .h(7), .h(8), .d(7), .h(14), .d(14)], recommendedDiscard: [.h(14), .d(14)], reasoning: "Herz-Ass und Karo-Ass sind die beiden höchsten Karten. Ohne sie bleiben niedrige Folgen. Das garantiert keinen Nullsieg gegen jede Verteilung, vermeidet aber die ausdrücklich genannten Spitzenrisiken.", tip: "Bei Null zählt Deckung unter hohen Karten, nicht ihre Augen im Skat."),
        DiscardScenario(id: "vertieft-druecken-04", situation: "Null, Vorhand, gereizt 23. Lehrziel: Pikfreiheit herstellen und zugleich Karo bis auf die Sieben abbauen. Welche zwei Karten müssen weg?", deal: [.c(7), .c(8), .c(9), .c(11), .c(12), .h(7), .h(8), .h(9), .h(10), .d(7), .s(13), .d(12)], recommendedDiscard: [.s(13), .d(12)], reasoning: "Der alleinstehende Pik-König muss weg, ebenso Karo-Dame. Kreuz-Dame bleibt unter dieser Vorgabe bewusst in ihrer längeren Farbe. Die Kreuz-Lücke bei der Zehn bleibt ein Risiko, kein automatisch sicherer Null.", tip: "Ein hoher Einzelkönig ist anders zu bewerten als eine hohe Karte mit mehreren kleinen Karten darunter."),
        DiscardScenario(id: "vertieft-druecken-05", situation: "Pik, Hinterhand, gereizt 44. Lehrziel: Herzfreiheit herstellen, ohne einen Trumpf zu drücken. Wähle das einzige Paar.", deal: [.c(11), .s(11), .h(11), .d(11), .s(14), .s(10), .s(7), .h(14), .h(10), .c(14), .d(13), .d(7)], recommendedDiscard: [.h(14), .h(10)], reasoning: "Die zwei Herz-Seitenkarten sichern 21 Skataugen und schaffen Herzfreiheit. Herz-Bube bleibt ein Piktrumpf. Eine kleine Karo-Karte zu drücken würde das Ziel nicht erfüllen.", tip: "Ein gedrücktes Ass kann sinnvoll sein, wenn das konkrete Ziel eine freie Farbe und sichere Skataugen ist."),
        DiscardScenario(id: "vertieft-druecken-06", situation: "Grand, Vorhand, gereizt 72. Lehrziel: Alle Buben und die vollständige Kreuz-Seitenfolge behalten, zugleich herz- und karofrei werden. Welches Paar passt?", deal: [.c(11), .s(11), .h(11), .d(11), .c(14), .c(10), .c(13), .c(12), .c(9), .s(14), .h(12), .d(12)], recommendedDiscard: [.h(12), .d(12)], reasoning: "Herz-Dame und Karo-Dame sind die einzigen Seitenkarten ihrer Farben. Ihre sechs Augen gehen in den Skat; die Kreuzfolge und vier Buben bleiben. Im Grand zählt der Kreuz-Bube nicht zur Kreuz-Seitenfolge.", tip: "Länge ist ein Plan für zusätzliche Stiche. Trenne sie beim Sortieren von den vier Grandtrümpfen."),
        DiscardScenario(id: "vertieft-druecken-07", situation: "Karo, Mittelhand, gereizt 36. Lehrziel: Alle Trümpfe behalten und herzfrei werden. Welches Paar erfüllt das?", deal: [.c(11), .s(11), .h(11), .d(11), .d(14), .d(10), .d(9), .h(13), .h(12), .c(14), .s(14), .s(7)], recommendedDiscard: [.h(13), .h(12)], reasoning: "Herz-König und Herz-Dame sind die einzigen Herz-Seitenkarten. Beide zusammen sichern sieben Skataugen. Den Herz-Buben mitdrücken wäre unter dem Ziel, alle Trümpfe zu behalten, falsch.", tip: "Benannte Ziele machen die Lehrentscheidung prüfbar. Eine unbekannte gegnerische Verteilung erlaubt keinen absoluten Gewinnbeweis."),
        DiscardScenario(id: "vertieft-druecken-08", situation: "Kreuz, Vorhand, gereizt 60. Lehrziel: Alle sechs Trümpfe behalten und unter den übrigen Karten die maximale Augensumme drücken. Wähle das Paar.", deal: [.c(11), .s(11), .h(11), .d(11), .c(14), .c(10), .s(14), .d(14), .h(10), .s(13), .d(12), .h(7)], recommendedDiscard: [.s(14), .d(14)], reasoning: "Die zwei Seitenasse liefern 22 Skataugen, mehr als Ass und Zehn mit 21. Alle sechs Trümpfe bleiben. Das Lehrziel maximiert sichere Skataugen, es behauptet nicht die allgemein beste Gewinnstrategie.", tip: "Kreuz-Ass gehört hier zum Trumpfkern, Pik-Ass und Karo-Ass nicht. Der gleiche Kartenrang kann verschiedene Aufgaben haben.")
    ]

    static func question(_ id: String, _ prompt: String, _ answer: String, _ second: String,
                         _ third: String, _ explanation: String, _ tiles: [PlayingCard] = []) -> QuizQuestion {
        QuizQuestion(id: id, prompt: prompt, tiles: tiles, choices: [answer, second, third],
                     answerIndex: 0, explanation: explanation)
    }
}
