import Foundation

enum AppliedContent {
    static let bidding: [QuizQuestion] = [
        question("praxis-reizen-01", "Kreuz mit einem, Skataufnahme geplant. Ohne Schneider erwartest du 24. Mittelhand bietet 27. Reicht dein einfacher Spielwert zum Halten?", "Nein", "Ja", "Nur als Hinterhand", "Mit einem, Spiel zwei mal zwölf = 24. Wer 27 hält, braucht eine zusätzliche tatsächlich erreichte Stufe oder ein anderes ausreichend wertvolles Spiel."),
        question("praxis-reizen-02", "Pik mit zwei, Skataufnahme. Du erwartest mehr als 60, aber weniger als 90 Augen. Welche Reizhöhe ist durch diesen einfachen Wert gedeckt?", "33", "35", "44", "Mit zwei, Spiel drei: 3 × 11 = 33. 35 und 44 verlangen mehr Spielwert."),
        question("praxis-reizen-03", "Herz ohne einen, Skataufnahme, kein Schneider. Kreuz-Bube fehlt auch nach der Aufnahme. Welcher Spielwert ist gedeckt?", "20", "22", "30", "Ohne einen, Spiel zwei mal zehn = 20. Der fehlende Kreuz-Bube zählt als eine Spitze, nicht als null."),
        question("praxis-reizen-04", "Karo mit zwei, Skataufnahme, kein Schneider. Welche Reizhöhe deckt der einfache Wert gerade noch?", "27", "30", "36", "Mit zwei, Spiel drei mal neun = 27. Ein Reizschritt zu 30 geht über diesen Wert."),
        question("praxis-reizen-05", "Du planst Null mit Skataufnahme. Vorhand hält 23. Darfst du 24 sagen, wenn du ausschließlich diesen Nullwert als Deckung hast?", "Nein, Null zählt 23", "Ja, Null zählt 24", "Ja, Null hat keine Reizgrenze", "Du darfst zwar höher reizen, würdest mit einem Null für 23 aber überreizen. Diese Aufgabe fragt nach Deckung, nicht nach einem verbotenen Reizgebot."),
        question("praxis-reizen-06", "Du hältst 35 und möchtest ein Nullspiel mit Skataufnahme, aber nicht offen spielen. Deckt diese Ansage 35?", "Nein, sie zählt nur 23", "Ja, sie zählt 35", "Ja, jeder Null zählt 46", "Null-Hand zählt 35, erfordert aber Verzicht auf Skataufnahme. Nach Aufnahme deckt nur ein ausreichend höherer Spielwert das Gebot."),
        question("praxis-reizen-07", "Grand mit einem, Skataufnahme, kein Schneider. Welche der angebotenen Reizhöhen ist durch den einfachen Wert gedeckt?", "48", "50", "59", "Mit einem, Spiel zwei mal 24 = 48. Ein Grand ist nicht automatisch mindestens 72 wert."),
        question("praxis-reizen-08", "Du findest Kreuz-Bube im Skat. Pik-Bube fehlt, Herz-Bube war bereits auf deiner Hand. Wie zählen die Spitzen bei Grand jetzt?", "Mit einem", "Ohne zwei", "Mit zwei", "Die Folge startet oben beim Kreuz-Buben und endet vor dem fehlenden Pik-Buben. Der Herz-Bube unter der Lücke verlängert sie nicht."),
        question("praxis-reizen-09", "Du hast Kreuz- und Pik-Bube, aber keinen Herz-Buben. Der Karo-Bube liegt im aufgenommenen Skat. Wie viele Spitzen zählen beim Grand?", "Mit zwei", "Mit drei", "Mit vier", "Eine Lücke stoppt die Spitzenfolge. Der Karo-Bube wird nicht einfach zu den beiden höchsten Buben addiert."),
        question("praxis-reizen-10", "Herz mit einem, Hand statt Skataufnahme, kein Schneider. Der Skat ändert die Spitzen nicht. Wie viel höher ist der Wert als mit Aufnahme?", "10 Punkte höher", "20 Punkte höher", "Kein Unterschied", "Hand fügt eine Stufe hinzu. Der Herzgrundwert zehn macht aus 20 einen Wert von 30."),
        question("praxis-reizen-11", "Mittelhand passt sofort. Wer kann nun Hinterhand durch Halten oder Passen beantworten?", "Vorhand", "Mittelhand", "Der Geber immer", "Nachdem Mittelhand ausscheidet, reizt Hinterhand gegen Vorhand. Die Positionen gelten, nicht eine pauschale Sonderrolle des Gebers."),
        question("praxis-reizen-12", "Du hast Kreuz-Bube gedrückt, Pik-Bube bleibt auf der Hand. Herz-Bube fehlt. Wie zählt Grand hinsichtlich der Spitzen?", "Mit zwei", "Ohne einen", "Mit einem", "Für die Spitzen zählt auch der gedrückte Skat. Kreuz-Bube und Pik-Bube gehören dir beide, daher mit zwei. Erst der fehlende Herz-Bube beendet die Folge.")
    ]

    static let tricks: [QuizQuestion] = [
        question("praxis-stich-01", "Grand. Kreuz-Sieben ist angespielt. Deine vollständige Resthand ist Kreuz-Bube und Herz-Ass. Welche Karten darfst du legen?", "Beide", "Nur Kreuz-Bube", "Nur Herz-Ass", "Der Kreuz-Bube gehört zu Trumpf, nicht zur Kreuz-Seitenfarbe. Du bist kreuzfrei und darfst stechen oder abwerfen.", [.c(11), .h(14)]),
        question("praxis-stich-02", "Herzspiel. Herz-Sieben ist angespielt. Deine Resthand ist Pik-Bube und Karo-Ass. Welche Karte ist Pflicht?", "Pik-Bube", "Karo-Ass", "Du darfst wählen", "Herz fordert Trumpf. Pik-Bube ist ebenfalls Herztrumpf und muss bedient werden.", [.s(11), .d(14)]),
        question("praxis-stich-03", "Grand. Pik-Bube ist angespielt. Du hast Herz-Bube und Pik-Ass. Welche Karte musst du legen?", "Herz-Bube", "Pik-Ass", "Beide sind erlaubt", "Ein Bube fordert Trumpf. Pik-Ass ist eine Seitenkarte und darf mit vorhandenem Herz-Buben nicht als Bedienung gelten.", [.h(11), .s(14)]),
        question("praxis-stich-04", "Null. Kreuz-Sieben ist angespielt. Deine Resthand ist Kreuz-Bube und Herz-Sieben. Welche Karte musst du legen?", "Kreuz-Bube", "Herz-Sieben", "Beide sind erlaubt", "Im Null gehören Buben zur aufgedruckten Farbe. Kreuz-Bube muss Kreuz bedienen, auch wenn er einen unerwünschten Stich verursachen könnte.", [.c(11), .h(7)]),
        question("praxis-stich-05", "Grand. Herz-Zehn, Herz-König und Herz-Dame liegen in dieser Reihenfolge. Kein Trumpf. Wer gewinnt?", "Herz-Zehn", "Herz-König", "Herz-Dame", "In Farbe und Grand steht die Zehn über König und Dame. Der Stich zählt 17 Augen.", [.h(10), .h(13), .h(12)]),
        question("praxis-stich-06", "Null. Herz-Zehn, Herz-König und Herz-Dame liegen in dieser Reihenfolge. Wer gewinnt?", "Herz-König", "Herz-Zehn", "Herz-Dame", "Im Null ist die Reihenfolge anders. König schlägt Dame und Zehn. Buben sind keine Trümpfe.", [.h(10), .h(13), .h(12)]),
        question("praxis-stich-07", "Karo. Kreuz-Ass, Pik-Ass und Herz-Ass liegen in dieser Reihenfolge. Niemand hat Trumpf gelegt. Wer gewinnt?", "Kreuz-Ass", "Pik-Ass", "Herz-Ass", "Die angespielte Farbe ist Kreuz. Die fremden Asse sind Abwürfe und können diesen Stich ohne Trumpf nicht gewinnen.", [.c(14), .s(14), .h(14)]),
        question("praxis-stich-08", "Grand. Karo-Ass, Karo-Zehn und Karo-Bube liegen in dieser Reihenfolge. Wer gewinnt?", "Karo-Bube", "Karo-Ass", "Karo-Zehn", "Karo-Bube ist im Grand Trumpf und schlägt die beiden Seitenkarten. Der vollständige Stich enthält 23 Augen.", [.d(14), .d(10), .d(11)]),
        question("praxis-stich-09", "Null. Karo-Ass, Karo-Zehn und Karo-Bube liegen in dieser Reihenfolge. Wer gewinnt?", "Karo-Ass", "Karo-Bube", "Karo-Zehn", "Bei Null ist der Bube kein Trumpf. Das Ass bleibt die höchste Karte der Farbe.", [.d(14), .d(10), .d(11)]),
        question("praxis-stich-10", "Herz. Kreuz-Ass ist angespielt. Du hast Kreuz-Sieben und Herz-Bube. Darfst du mit dem Buben stechen?", "Nein", "Ja", "Nur in Hinterhand", "Mit einer Kreuz-Seitenkarte musst du Kreuz bedienen. Ein vorhandener Trumpf hebt diese Pflicht nicht auf.", [.c(7), .h(11)]),
        question("praxis-stich-11", "Pik. Karo-Zehn ist angespielt. Du bist karofrei und hältst Pik-Sieben sowie Herz-Sieben. Musst du stechen?", "Nein, beide sind legal", "Ja, Pik-Sieben ist Pflicht", "Nein, du darfst nur Herz legen", "Die internationale Regel kennt keine allgemeine Stichpflicht. Ohne Karo darfst du stechen oder abwerfen.", [.s(7), .h(7)]),
        question("praxis-stich-12", "Grand. Du gewinnst einen Stich aus Kreuz-Bube, Pik-Bube und Herz-Bube. Wie viele Augen nimmst du mit?", "6", "3", "0", "Jeder Bube zählt zwei Augen. Drei Buben ergeben sechs, unabhängig davon, welcher Bube den Stich gewinnt.", [.c(11), .s(11), .h(11)])
    ]

    private static func question(_ id: String, _ prompt: String, _ answer: String, _ second: String,
                                 _ third: String, _ explanation: String, _ tiles: [PlayingCard] = []) -> QuizQuestion {
        AdvancedContent.question(id, prompt, answer, second, third, explanation, tiles)
    }
}
